### ISSUE TITLE
Italic for .md files

### ISSUE THREAD

**Issue by timsofteng** [ellisonleao/gruvbox.nvim#53] opened 2021-06-15 18:07 UTC
Hello. Is it any way to add italic style text displaying for md files?

**Comment by ellisonleao** [comment] 2021-06-19 02:06
not sure what you are meaning. Can you elaborate?

**Comment by timsofteng** [comment] 2021-06-19 11:38
> not sure what you are meaning. Can you elaborate?

When I work on .md files I expect to see italic text as italic.

![image](https://user-images.githubusercontent.com/51912173/122641127-f1697d80-d10b-11eb-8200-0d3c07b23c11.png)

Is it possible to implement itailc text into .md files?

**Comment by robbienohra** [comment] 2021-11-21 19:33
I've noticed a similar issue

**Comment by robbienohra** [comment] 2021-11-21 19:34
It doesn't appear to be an issue with `morhetz/gruvbox`

**Comment by ellisonleao** [comment] 2021-12-11 03:46
hey @robbienohra @timsofteng are you using `vim.g.italicize_strings = true` in your config? It's not enabled by default

**Comment by robbienohra** [comment] 2021-12-11 04:17
@ellisonleao thanks for the response, what would this setting look like at the level of `init.vim`?

**Comment by robbienohra** [comment] 2021-12-11 04:20
if what you meant is
```
let g:vim_italicize_strings = 1
```

then that still doesn't seem to work 🤔

**Comment by robbienohra** [comment] 2021-12-11 04:23
For the record at the `gruvbox`-level I've always had

```
let g:gruvbox_italic = 1
```

**Comment by ellisonleao** [comment] 2021-12-11 12:59
@robbienohra this plugin has the same API config values as the original one, so it should be:

```vim
let g:gruvbox_italicize_strings = 1
```
the `g:gruvbox_italic` is already true by default so you shouldn't need to reconfig it

**Comment by robbienohra** [comment] 2021-12-11 17:24
That did the trick! 🥳  Thank you! 🙏

**Comment by robbienohra** [comment] 2021-12-11 17:29
One thing worth noting though is that this now italicizes _all_ strings and not just the markdown italic case.

I suppose I can just add a simple-filetype rule though that conditionally sets this to `1` for markdown files

**Comment by ellisonleao** [comment] 2021-12-11 18:56
>One thing worth noting though is that this now italicizes all strings and not just the markdown italic case.

yes, that's the behaviour

**Comment by ellisonleao** [comment] 2021-12-11 19:14
@timsofteng lmk if we can close this issue

**Comment by robbienohra** [comment] 2021-12-12 00:06
I think it's also worth mentioning that markdown italicized words such as `_hello_` in `'morhetz/gruvbox'`

**Comment by ellisonleao** [comment] 2021-12-12 00:21
@robbienohra can you confirm if the community version has that behaviour as well? this repo follows the code over there and not the original one

**Comment by robbienohra** [comment] 2021-12-12 00:28
Confirmed the community version doesn't require the config either for markdown italics to work 🤔

**Comment by ellisonleao** [comment] 2021-12-12 00:31
cool, thanks for checking. Will investigate

**Comment by robbienohra** [comment] 2021-12-12 00:35
Thanks!

[This](https://github.com/gruvbox-community/gruvbox/blob/master/colors/gruvbox.vim#L1531) seems to be where italicization for markdown files is handled in the community version

**Comment by ellisonleao** [comment] 2021-12-12 00:48
@robbienohra just pushed a fix for markdown while i check the other languages, can you validate please?

**Comment by robbienohra** [comment] 2021-12-12 01:32
Still no cigar 😞

**Comment by ellisonleao** [comment] 2021-12-12 02:25
@robbienohra can you share you config? Here's a screenshot of my editor. I am not adding any italic configs, just setting the colorscheme
![Screenshot from 2021-12-11 23-24-59](https://user-images.githubusercontent.com/178641/145698023-adedf43f-8034-4a54-926e-83c2467fd72d.png)

**Comment by robbienohra** [comment] 2021-12-12 02:55
For purposes of investigation I just reduced it to this:

```
call plug#begin('~/.vim/plugged')
Plug 'rktjmp/lush.nvim'
Plug 'ellisonleao/gruvbox.nvim'
Plug 'plasticboy/vim-markdown'
call plug#end()

colorscheme gruvbox
```

are you perhaps using a different markdown plugin?

**Comment by robbienohra** [comment] 2021-12-12 02:59
Hm...actually wait I may have found a clue

**Comment by robbienohra** [comment] 2021-12-12 03:03
I wasn't able to produce a successful case with the other libs with this stripped config — so there must be a clue in my full config.

Here's the full one:

```set nocompatible
set ignorecase
set nobackup
set nowritebackup
set encoding=UTF-8
set number
set undodir=~/.configs/nvim/undodir
set undofile
set ls=2
set termguicolors
set textwidth=79
set cmdheight=1
set formatoptions+=l
set shm=at
set shortmess+=W
set shiftwidth=2
set updatetime=100
set norelativenumber
set lazyredraw
set nocursorcolumn
set nocursorline
set synmaxcol=200
set foldmethod=marker
set re=0
set timeoutlen=1000 ttimeoutlen=0
set completeopt=menuone,noinsert,noselect
set pastetoggle=<F3>
" for cursor focus
set splitright
set splitbelow

filetype plugin indent on
filetype on
highlight VertSplit cterm=NONE

" plugins

call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-vinegar'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-commentary'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/vim-peekaboo'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'} 
Plug 'hoob3rt/lualine.nvim'
Plug 'mhinz/vim-signify'
Plug 'ruanyl/vim-gh-line'
Plug 'norcalli/nvim-colorizer.lua'
Plug 'plasticboy/vim-markdown'
Plug 'rktjmp/lush.nvim'
Plug 'ellisonleao/gruvbox.nvim'
" Plug 'morhetz/gruvbox'
Plug 'reedes/vim-pencil'
call plug#end()

" themes
set background=dark
let g:gruvbox_invert_selection=0
let g:gruvbox_contrast_dark = 'hard'
let g:gruvbox_sign_column = 'bg0'
let g:gruvbox_italic = 1
let g:gruvbox_italicize_strings = 1
colorscheme gruvbox

let g:fzf_colors =
  \ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

" markdown
let g:vim_markdown_strikethrough = 1
let g:vim_markdown_conceal_code_blocks = 1
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_json_frontmatter = 1
let g:vim_markdown_no_extensions_in_markdown = 1
let g:vim_markdown_new_list_item_indent = 0
let g:vim_markdown_auto_insert_bullets = 1
let g:tex_conceal = "$"
let g:vim_markdown_math = 1
set conceallevel=2

" coc-nvim 

let g:coc_global_extensions = [
		\"coc-clangd", 
		\"coc-css", 
		\"coc-emmet",
		\"coc-html",
		\"coc-json", 
		\"coc-prettier", 
		\"coc-pyright", 
		\"coc-sql", 
		\"coc-tsserver",
		\"coc-eslint",
		\"coc-yaml",
		\"coc-toml",
		\"coc-markdownlint",
		\"coc-snippets"]

nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gv :call CocAction('jumpDefinition', 'vsplit')<CR>
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
nmap <silent> <leader>a  <Plug>(coc-codeaction-selected)
nmap <silent> <leader>rn <Plug>(coc-rename)
command! -nargs=0 Format :call CocAction('format')
command! -nargs=0 OR :call CocAction('runCommand', 'editor.action.organizeImport')
command! -nargs=0 Prettier :call CocAction('runCommand', 'prettier.formatFile')
nnoremap <silent> <leader>p :Prettier<CR>

hi! CocErrorSign guifg=#d1666a
hi! CocInfoSign guibg=#353b45
hi! CocWarningSign guifg=#d1cd66

imap <C-l> <Plug>(coc-snippets-expand)

" python indentation

au BufNewFile,BufRead *.py set tabstop=4 softtabstop=4 shiftwidth=4 expandtab smarttab autoindent

" fzf

nnoremap <silent> <C-t> :Files <CR>
nnoremap <silent> <C-f> :Rg<CR>

" mappings

" fugitive

map <leader>dv :Gvdiffsplit!

" compile and run c++ program

autocmd FileType cpp nnoremap <C-c> :!g++ -o  %:r.out % -std=c++11<Enter>
autocmd FileType cpp nnoremap <C-x> :!./%:r.out

" find and replace

map <leader>f :%s/

" misc

nnoremap tl  :tabprev<CR>
nnoremap tu  :tabnext<CR>

autocmd BufReadPre,BufNewFile * let b:did_ftplugin = 1

nnoremap ZZ ZZ
nnoremap Q ZQ
nnoremap <silent> <C-S> :update<CR>
inoremap <silent> <C-S> <Esc>:update<CR>
vnoremap <C-c> :w !pbcopy<CR><CR>
" clear search
noremap <silent> <C-k> :let @/ = ""<CR>

" black hole register
nmap <S-d> "_dd
nmap <S-b> dvb
" nmap <S-w> ciw
nmap <S-w> diw

" nvim

let g:loaded_perl_provider = 0
let g:loaded_ruby_provider = 0

" lua configs

lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained", 
  highlight = {
    enable = true,            
    additional_vim_regex_highlighting = false,
  },
}

require('lualine').setup {
  options = {
    theme = 'gruvbox_dark',
    icons_enabled = false
  }
}

require'colorizer'.setup()
EOF

" abbreviations

iabbrev <expr> dts strftime("%Y-%m-%d")

" commenter

autocmd FileType vim setlocal commentstring=\"\ %s
autocmd FileType yaml,sh setlocal commentstring=#\ %s
autocmd FileType markdown setlocal commentstring=<!--\ %s\ -->

" " pencil

" augroup pencil
"   autocmd!
"   autocmd FileType markdown,mkd call pencil#init()
"   autocmd FileType text         call pencil#init()
" augroup END
```

**Comment by robbienohra** [comment] 2021-12-12 03:07
(Minus the new italicize string variable assignment)

**Comment by robbienohra** [comment] 2021-12-12 03:25
OK here we go:

```
call plug#begin('~/.vim/plugged')
Plug 'plasticboy/vim-markdown'
Plug 'rktjmp/lush.nvim'
" Plug 'ellisonleao/gruvbox.nvim'
Plug 'gruvbox-community/gruvbox'
call plug#end()

" themes
let g:gruvbox_invert_selection=0
let g:gruvbox_contrast_dark = 'hard'
let g:gruvbox_sign_column = 'bg0'
let g:gruvbox_italic = 1
colorscheme gruvbox

" markdown
let g:vim_markdown_strikethrough = 1
let g:vim_markdown_conceal_code_blocks = 1
let g:vim_markdown_folding_disabled = 1
```

![image](https://user-images.githubusercontent.com/28514482/145698996-c438756c-1786-4b4d-9bbe-3e930faa1e65.png)

![image](https://user-images.githubusercontent.com/28514482/145699000-fba05596-625b-45db-a04d-a5c80f4d4dec.png)

The screenshot is what I see when I toggle between the plugin here and the community one (with the community one showing the italics)

**Comment by robbienohra** [comment] 2021-12-18 19:12
@ellisonleao is there anything else I can do to help debug?

**Comment by ellisonleao** [comment] 2022-01-09 01:02
hey @robbienohra i was looking at the plugin you use for markdown and looks like it uses a HTML highlight group which was missing in this repo for getting italics and bold in place for markdown files. I just pushed them (alongside other fixes). Can you pull latest and check again please?

**Comment by robbienohra** [comment] 2022-01-09 22:55
@ellisonleao eehh it looks like it's working now! 🥳 

Thanks a bunch, buddy!

**Closed** 2022-01-09 23:07 UTC
