### ISSUE TITLE
[Question] how to do `vim.g.gruvbox_sign_column = "bg0"` with the new config system?

### ISSUE THREAD

**Issue by MaxVerevkin** [ellisonleao/gruvbox.nvim#129] opened 2022-06-29 15:59 UTC
I used to have `vim.g.gruvbox_sign_column = "bg0"` in my config. How can I achieve the same behavior with the new configuration system?

**Comment by MaxVerevkin** [comment] 2022-06-29 18:30
Before:
![image](https://user-images.githubusercontent.com/34583604/176509933-e7c21e5f-5f85-4973-bbe5-59575d7b9ab9.png)


After: 
![image](https://user-images.githubusercontent.com/34583604/176509751-2c2591c9-47fc-431c-88c4-2be3db3e41d1.png)

**Comment by ellisonleao** [comment] 2022-06-29 20:47
@MaxVerevkin can you explain a little bit more? What is your config and expected color?

**Comment by MaxVerevkin** [comment] 2022-06-29 20:51
@ellisonleao with the new config system and the new workaround, git-signs have inconsistent background with the rest of the sign column (lines 85-88 on my screenshots).

**Comment by ellisonleao** [comment] 2022-06-29 20:55
@MaxVerevkin have you tried the override?

**Comment by MaxVerevkin** [comment] 2022-06-29 20:59
Yes. Here's how it looks w/o this override:
![image](https://user-images.githubusercontent.com/34583604/176543750-9239722e-2ac5-4f3a-9dd9-82d6e75fc506.png)

**Comment by ellisonleao** [comment] 2022-06-30 01:08
@MaxVerevkin ok i was able to override the following:

```lua
-- make sure to use the same bg as your contrast (dark0 for default contrast, dark0_hard for hard contrast and dark0_soft for soft contrast)
local colors = require("gruvbox.palette")
require("gruvbox").setup({
  overrides = {
    GruvboxRedSign = { fg = colors.red, bg = colors.dark0, reverse = false },
    GruvboxGreenSign = { fg = colors.green, bg = colors.dark0, reverse = false },
    GruvboxYellowSign = { fg = colors.yellow, bg = colors.dark0, reverse = false },
    GruvboxBlueSign = { fg = colors.blue, bg = colors.dark0, reverse = false },
    GruvboxPurpleSign = { fg = colors.purple, bg = colors.dark0, reverse = false },
    GruvboxAquaSign = { fg = colors.aqua, bg = colors.dark0, reverse = false },
    GruvboxOrangeSign = { fg = colors.orange, bg = colors.dark0, reverse = false },
  }
})
```
![Screenshot from 2022-06-29 22-06-47](https://user-images.githubusercontent.com/178641/176571280-2e18593a-82bb-4c81-bfec-03baf6af95bc.png)


Unfortunately the old gruvbox colorscheme is way too attached to specific color configs. I will need to find a way to balance this with the new config system.

**Comment by shibotto** [comment] 2022-07-31 20:05
How are you using, to name one, `colors.red`? Inside `gruvbox.palette` only the variants are defined (bright, natural, faded).

**Comment by ellisonleao** [comment] 2022-08-01 02:17
@shibotto actually you can't now. This was a high-level example, but you can use any color you want. If you wish to use the gruvbox colors, you will need to get the exact name from the palette for now.

**Comment by ellisonleao** [comment] 2022-08-01 02:17
Will close this one since we didn't get any response so far. Please feel free to open another one if the problem is still not fixed

**Closed by ellisonleao** 2022-08-01 02:17 UTC

**Comment by MaxVerevkin** [comment] 2023-04-03 05:41
> @MaxVerevkin ok i was able to override the following:
> 
> ```lua
> -- make sure to use the same bg as your contrast (dark0 for default contrast, dark0_hard for hard contrast and dark0_soft for soft contrast)
> local colors = require("gruvbox.palette")
> require("gruvbox").setup({
>   overrides = {
>     GruvboxRedSign = { fg = colors.red, bg = colors.dark0, reverse = false },
>     GruvboxGreenSign = { fg = colors.green, bg = colors.dark0, reverse = false },
>     GruvboxYellowSign = { fg = colors.yellow, bg = colors.dark0, reverse = false },
>     GruvboxBlueSign = { fg = colors.blue, bg = colors.dark0, reverse = false },
>     GruvboxPurpleSign = { fg = colors.purple, bg = colors.dark0, reverse = false },
>     GruvboxAquaSign = { fg = colors.aqua, bg = colors.dark0, reverse = false },
>     GruvboxOrangeSign = { fg = colors.orange, bg = colors.dark0, reverse = false },
>   }
> })
> ```

This does not work for `set background=light`. I can't just change the overrides to match background because neovim sets it automatically based on the background of the terminal. `if backgound == "light"` wouldn't work because it is set after the config is loaded. Any thoughts/ideas?
