### ISSUE TITLE
Italic comments not working on latest commit

### ISSUE THREAD

**Issue by manuelcattelan** [ellisonleao/gruvbox.nvim#113] opened 2022-04-20 07:07 UTC
I use packer for configuring all my plugins and reverting to the February commit enables italic comments while updating to latest breaks them and there's no way of making them work.

I'm very new to GitHub and Neovim so if you need any information regarding my config please don't get mad and I'll provide :)

**Comment by cryptomilk** [comment] 2022-04-22 06:57
It looks like several options you can set don't work anymore. I turned off italic and currently I have italic fonts. Also lualine seems to be affected by the change.

**Comment by fitrh** [comment] 2022-04-22 11:48
That's because the [settings](https://github.com/ellisonleao/gruvbox.nvim/blob/e5455e9ecdcf6f6c95d2d8b15f44c43c389e77b0/lua/gruvbox/base.lua#L24) say `italicize_comments` while the [`Comment`](https://github.com/ellisonleao/gruvbox.nvim/blob/e5455e9ecdcf6f6c95d2d8b15f44c43c389e77b0/lua/gruvbox/base.lua#L285) group still use `italic_comments`

**Comment by fitrh** [comment] 2022-04-22 11:51
The workaround for this is to set `vim.g.gruvbox_italic_comments = true` before loading the theme

**Comment by storopoli** [comment] 2022-04-22 12:17
That fixed for me @fitrh thanks!

**Comment by manuelcattelan** [comment] 2022-04-22 12:57
Thank you @cryptomilk and @fitrh , I was able to fix the issue!

**Comment by fitrh** [comment] 2022-04-22 13:04
@manuelcattelan I think it is better to leave this issue open until there is an upstream fix

**Comment by ellisonleao** [comment] 2022-04-22 16:18
Hey guys I am reopening this until I can proper fix the issue. Thanks for raising that up

**Comment by ellisonleao** [comment] 2022-04-22 20:20
just pushed a fix

**Comment by manuelcattelan** [comment] 2022-04-23 08:50
Sorry guys, I didn’t think a fix was on the way since the workaround was so simple. Thanks @ellisonleao for the update!

**Comment by storopoli** [comment] 2022-04-23 09:50
Now we can close, I can confirm that the fix works.

**Closed** 2022-04-23 12:16 UTC
